<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(CapkitPlatform)' == 'windows'">net10.0-windows</TargetFramework>
    <TargetFramework Condition="'$(CapkitPlatform)' != 'windows'">net10.0</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Capkit.Avalonia\Capkit.Avalonia.csproj" />
    <ProjectReference Include="..\Capkit.HelpersLib\Capkit.HelpersLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
