<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(CapkitPlatform)' == 'windows'">net10.0-windows</TargetFramework>
    <TargetFramework Condition="'$(CapkitPlatform)' != 'windows'">net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <UseSystemDrawing>true</UseSystemDrawing>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Capkit.Avalonia\Capkit.Avalonia.csproj" />
    <ProjectReference Include="..\Capkit.HelpersLib\Capkit.HelpersLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
